import express from 'express';
import userRoutes from './routes/userRoutes'
import blogRoutes from './routes/blogRoutes';
import swaggerUi from 'swagger-ui-express';
import swaggerJsDoc from 'swagger-jsdoc';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
app.use(express.json());

const swaggerDefinition = {
	openapi: '3.0.0',
	info: {
		title: 'Medical Departure Blog System API',
		version: '1.0.0',
		description: 'Medical Departure Blog System API with autogenerated swagger doc',
	},
	servers: [
	{
		url: `http://localhost:${process.env.PORT || 3000}`,
	    },
	],
};

const options = {
swaggerDefinition,
apis: ['./src/routes/*.ts'],
};

const swaggerSpec = swaggerJsDoc(options);

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.use('/users', userRoutes);
app.use('/blogs', blogRoutes);

export default app;